version: '3.7'
services:
  shore-postgres-db:
    image: postgres:11.4
    container_name: shore-postgres-db
    restart: always
    environment:
      POSTGRES_USER: root_user
      POSTGRES_PASSWORD: root_password
      POSTGRES_DB: shore
    ports:
      - "15432:5432"
    networks:
      - web-db-net
    env_file:
      - .env

  ebay-alerts:
    build: .
    restart: always
    command: bash -c "/bin/sh start.sh"
    container_name: ebay-alerts
    volumes:
      - .:/ebay-alerts
    ports:
      - "5000:80"
    depends_on:
      - shore-postgres-db
    networks:
      - web-db-net
    env_file:
      - .env

  celery_worker:
    image: celery_worker
    build: .
    restart: always
    command: bash -c "/bin/sh celerystart.sh"
    container_name: worker
    volumes:
      - .:/ebay-alerts
    networks:
      - web-db-net
    depends_on:
      - ebay-alerts
    env_file:
      - .env

  beat:
    image: beat
    build: .
    restart: always
    command: bash -c "/bin/bash celeryscheduler.sh"
    container_name: beat
    volumes:
      - .:/ebay-alerts
    networks:
      - web-db-net
    depends_on:
      - ebay-alerts
    env_file:
      - .env

  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
    networks:
      - web-db-net
    env_file:
      - .env


networks:
  web-db-net:
    name: "web_db_net"